Repository grafana/logs-drilldown, pull requests merged in 2024-12, with the labels that each got.

#924 Field labels: histogram option for numeric fields
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/services/analytics.ts
  src/services/store.ts
Labels: enhancement

#938 Upgrade scenes to v5.29.0
  package.json
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/TimeSeriesLimit.ts
  src/Components/ServiceScene/Breakdowns/TimeSeriesLimitSeriesTitleItem.tsx
  tests/appNavigation.spec.ts
  yarn.lock
Labels: chore

#940 Breakdown panels: Add shared crosshairs
  src/Components/ServiceScene/BreakdownViews.ts
  src/services/labels.ts
Labels: enhancement

#944 Logs Panel: Combine wrapLogMessage with prettifyLogMessage
  src/Components/ServiceScene/LogOptionsScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
Labels: frontline

#936 Value breakdowns: Update UI
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/Breakdowns/AddToExplorationButton.tsx
  src/Components/ServiceScene/Breakdowns/BreakdownSearchScene.tsx
  src/Components/ServiceScene/Breakdowns/ByFrameRepeater.tsx
  src/Components/ServiceScene/Breakdowns/FieldSelector.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LayoutSwitcher.tsx
  src/Components/ServiceScene/Breakdowns/NoMatchingLabelsScene.tsx
  src/Components/ServiceScene/Breakdowns/Panels/ValueSummary.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/Breakdowns/SortByScene.tsx
  src/Components/ServiceScene/Breakdowns/TimeSeriesLimitSeriesTitleItem.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/LogsVolumePanel.tsx
  src/services/fields.ts
  src/services/scenes.ts
  src/services/store.ts
  src/services/variableGetters.ts
  src/services/variableHelpers.ts
  tests/exploreServices.spec.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/exploreServicesJsonBreakDown.spec.ts
  tests/exploreServicesJsonMixedBreakDown.spec.ts
Labels: enhancement

#937 Timeseries panels: Map field display names to color
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/fields.ts
  src/services/panel.ts
Labels: enhancement

#946 Panels: Keybindings
  project-words.txt
  src/Components/IndexScene/IndexScene.tsx
  src/Components/Panels/PanelMenu.tsx
  src/services/KeybindingSet.ts
  src/services/Mousetrap.ts
  src/services/keyboardShortcuts.ts
  src/services/scenes.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement

#948 chore: update livereload plugin port
  webpack.config.ts
Labels: chore

#955 fix(LogsVolumePanel): fix display of visible range when using cached data
  src/Components/ServiceScene/LogsVolumePanel.tsx
Labels: bug

#956 Line filter: add case sensitive line filter state to local storage
  project-words.txt
  src/Components/ServiceScene/LineFilterScene.tsx
  src/services/store.ts
Labels: enhancement

#960 Keybindings: support time range copy/paste
  src/Components/IndexScene/IndexScene.tsx
  src/services/keyboardShortcuts.test.ts
  src/services/keyboardShortcuts.ts
  src/services/narrowing.ts
Labels: enhancement

#951 Logs Tab: Show log line count
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/ActionBarScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToExplorationButton.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.test.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/LogsVolumePanel.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/TagKeysProviders.ts
  src/services/TagValuesProviders.ts
  src/services/datasource.test.ts
  src/services/datasource.ts
  src/services/datasourceTypes.ts
  src/services/logql.ts
  src/services/lokiQuery.ts
  src/services/metadata.ts
  src/services/panel.ts
  src/services/query.ts
  src/services/scenes.ts
  src/services/shardQuerySplitting.test.ts
  src/services/shardQuerySplitting.ts
  tests/exploreServices.spec.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/fixtures/explore.ts
Labels: enhancement

#968 fix(panel-menu): menu throwing error in logs table
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  tests/exploreServicesBreakDown.spec.ts
Labels: bug

#965 fix(panelmenu): `Investigations` causing multiple same keys
  src/Components/Panels/PanelMenu.tsx
Labels: bug
