Repository grafana/logs-drilldown, pull requests merged in 2024-11, with the labels that each got.

#867 Fix: tsc-files ignores tsconfig.json when called through husky hooks
  .lintstagedrc.js
  src/img/custom.d.ts
Labels: chore, no-changelog

#877 fix: console error when undefined jsondata.interval
  src/Components/IndexScene/IndexScene.tsx
Labels: bug

#868 ServiceSelectionScene: Manual query runners
  project-words.txt
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/panel.ts
  src/services/scenes.ts
  tests/exploreServices.spec.ts
  tests/mocks/getMockVolumeApiResponse.ts
  tests/mocks/mockVolumeApiResponse.ts
Labels: chore

#871 Detected fields: Use detected_fields response to determine if avg_over_time query should be run
  src/services/fields.ts
  src/services/variables.ts
Labels: bug

#908 Fix favoriting on label select
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.test.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldSelector.test.tsx
  src/Components/ServiceScene/Breakdowns/FieldSelector.tsx
  src/Components/ServiceSelectionScene/FavoriteServiceHeaderActionScene.tsx
  src/Components/ServiceSelectionScene/SelectServiceButton.tsx
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/TagValuesProviders.ts
  src/services/favorites.ts
  src/services/query.ts
  src/services/store.ts
  tests/exploreServices.spec.ts
  tests/fixtures/explore.ts
Labels: bug

#894 Panel UI: Numeric filtering
  docker-compose.local.yaml
  generator/generator.go
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/NumericFilterPopoverScene.test.ts
  src/Components/ServiceScene/Breakdowns/NumericFilterPopoverScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/fields.ts
  src/services/filterTypes.ts
  src/services/query.ts
  src/services/testIds.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement, bet

#914 Webpack: upgrade to 5.95
  package.json
  yarn.lock
Labels: chore

#920 Logs Panel: move log panel options and add sort order
  project-words.txt
  src/Components/ServiceScene/LogOptionsScene.test.tsx
  src/Components/ServiceScene/LogOptionsScene.tsx
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/__mocks__/LogsListScene.tsx
  src/Components/Table/LogsHeaderActions.tsx
  src/services/store.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/fixtures/explore.ts
Labels: enhancement

#892 Panel Menus
  config/loki-config.yaml
  docker-compose.local.yaml
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/Breakdowns/AddToExplorationButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/GoToExploreButton.tsx
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/LogsVolumePanel.tsx
  src/services/analytics.ts
  src/services/fields.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement

#928 fix(firefox-panel-hidden): add position absolute
  src/Components/Panels/PanelMenu.tsx
Labels: bug
