Repository grafana/logs-drilldown, pull requests merged in 2024-09, with the labels that each got.

#743 fix: grafana image tag
  docker-compose.yaml
Labels: bug

#579 chore: replace react-beautiful-dnd with successor
  cspell.config.json
  package.json
  project-words.txt
  src/Components/Table/ColumnSelection/LogsTableActiveFields.tsx
  tests/matchers.ts
  yarn.lock
Labels: core-changes-required

#779 fix(service-selection-scrolling): remove forced overflow scroll
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Labels: bug

#780 fix(patterns-breakdown): fix expression to create pattern key breakdown
  src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.test.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx
  tests/exploreServicesBreakDown.spec.ts
Labels: bug

#799 Frontend error handling: Better FetchError handling
  src/services/logger.ts
Labels: chore

#800 docs: Copyedit and replacing relrefs
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/get-started/_index.md
  docs/sources/labels-and-fields/_index.md
  docs/sources/ordering/_index.md
  docs/sources/patterns/_index.md
  docs/sources/troubleshooting/_index.md
Labels: type/docs

#490 Table: Persist user column resizing
  src/Components/Table/ColumnSelection/LogsTableActiveFields.tsx
  src/Components/Table/ColumnSelection/LogsTableNavField.tsx
  src/Components/Table/Context/TableColumnsContext.tsx
  src/Components/Table/LogsTableHeaderWrap.tsx
  src/Components/Table/Table.tsx
  tests/mocks/mockEmptyQueryApiResponse.ts
  tests/mocks/mockVolumeApiResponse.ts
Labels: enhancement
