Repository grafana/logs-drilldown, pull requests merged in 2024-08, with the labels that each got.

#650 chore: upgrade augurs
  package.json
  yarn.lock
Labels: chore

#659 ServiceScene: Fix invalid queries being called when navigating to service selection
  src/Components/ServiceScene/ServiceScene.tsx
  tests/exploreServices.spec.ts
Labels: bug

#666 Service selection scene: get service volume by partial or exact match
  docker-compose.dev.yaml
  playwright.config.ts
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/datasource.ts
  tests/exploreServices.spec.ts
Labels: bug

#430 Patterns: Logs sample
  docker-compose.yaml
  package.json
  project-words.txt
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
  src/Components/ServiceScene/Breakdowns/PatternsLogsSampleScene.tsx
  src/Components/ServiceScene/Breakdowns/PatternsTableExpandedRow.tsx
  src/plugin.json
  src/services/scenes.ts
  src/services/variables.ts
  yarn.lock
Labels: enhancement

#568 Table: clear selected line from url state after the table is initialized
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  src/Components/Table/Context/TableColumnsContext.tsx
  src/Components/Table/LineActionIcons.tsx
  src/Components/Table/LogsTableHeader.tsx
  src/Components/Table/Table.tsx
  src/Components/Table/TableProvider.tsx
  src/Components/Table/TableWrap.tsx
Labels: bug, core-changes-required

#668 Service selection: Results shown from wrong datasource after switching
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/query.ts
Labels: bug

#669 Fields breakdown: lazy loader e2e test
  project-words.txt
  tests/exploreServicesBreakDown.spec.ts
  tests/mocks/mockEmptyQueryApiResponse.ts
Labels: chore

#673 add play link to demonstrate product
  docs/sources/_index.md
Labels: documentation, type/docs

#684 ServiceScenes: Detected level variable not clearing after changing service
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/variables.ts
  tests/appNavigation.spec.ts
  tests/exploreServices.spec.ts
Labels: bug

#702 fix: bad links
  docs/sources/access/_index.md
Labels: bug, type/docs

#707 ServiceScene: prevent services with a mix of json and logfmt from request looping
  src/services/fields.test.ts
  src/services/fields.ts
Labels: bug

#682 Detected labels: Runtime datasource refactor
  cspell.config.json
  package.json
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/ActionBarScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.test.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/BreakdownSearchScene.tsx
  src/Components/ServiceScene/Breakdowns/ByFrameRepeater.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectFieldActionScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/Breakdowns/SortByScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/datasource.ts
  src/services/expressions.ts
  src/services/fields.ts
  src/services/metadata.ts
  src/services/navigate.test.ts
  src/services/panel.ts
  src/services/query.ts
  src/services/sorting.ts
  src/services/testIds.ts
  src/services/variables.ts
  tests/exploreServices.spec.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/fixtures/explore.ts
Labels: chore

#722 Value breakdowns: Add volume sort
  src/Components/ServiceScene/Breakdowns/SortByScene.tsx
Labels: enhancement

#703 Fields: include and exclude empty values
  src/Components/FilterButton.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectFieldActionScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/services/query.ts
  src/services/variables.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement
