Repository grafana/logs-drilldown, pull requests merged in 2024-10, with the labels that each got.

#815 docs: update installation instructions
  docs/sources/access/_index.md
Labels: type/docs

#831 Patterns: Fix broken data link in pattern viz
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsFrameScene.tsx
Labels: bug

#826 Structured metadata: Refactor into new variable
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.test.ts
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.test.ts
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  src/services/expressions.ts
  src/services/fields.ts
  src/services/routing.ts
  src/services/variableGetters.ts
  src/services/variables.ts
  tests/appNavigation.spec.ts
  tests/exploreServicesJsonBreakDown.spec.ts
  tests/exploreServicesJsonMixedBreakDown.spec.ts
Labels: enhancement

#845 Breakdowns: Changing primary label doesn't update tab count
  src/Components/ServiceScene/ServiceScene.tsx
  tests/exploreServices.spec.ts
Labels: bug

#853 Initial label docs
  docs/sources/get-started/_index.md
  docs/sources/images/initial-label-selector-cluster.png
  docs/sources/images/landing_page_index.png
Labels: type/docs

#860 fix: fix broken tsc-files command
  src/img/custom.d.ts
Labels: chore

#848 Ad hoc variables: add support for detected_field/.../values
  docker-compose.local.yaml
  project-words.txt
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/TagValuesProvider.ts
  src/services/fields.ts
  src/services/variableGetters.ts
  src/services/variables.ts
Labels: enhancement
