Repository grafana/logs-drilldown, pull requests merged in 2024-06, with the labels that each got.

#377 fix(patterns): fix bug introduced by using viewport units in styles
  src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Labels: bug

#390 Patterns: Smaller text font
  src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Labels: ui

#392 Chore: Refactor patterns breakdown
  src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/PatternsFrameScene.tsx
  src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Labels: ui, chore

#432 fix: label filter dropdown should show options
  src/Components/IndexScene/LayoutScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFilterButton.test.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/services/fields.ts
  src/services/scenes.ts
Labels: bug

#436 Logs Table UI: Legacy dataplane fix
  src/Components/Table/Context/TableColumnsContext.tsx
  src/Components/Table/LogLineCellComponent.tsx
  src/Components/Table/LogsTableHeader.tsx
  src/Components/Table/LogsTableHeaderWrap.tsx
  src/Components/Table/Table.tsx
  src/services/logsFrame.ts
Labels: bug

#444 Bug: Table - Add indexed labels to stream selector
  src/Components/ServiceScene/LogsTableScene.tsx
  src/Components/Table/Context/QueryContext.tsx
  src/Components/Table/TableProvider.tsx
Labels: bug

#446 Patterns: Use short units for count column
  src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Labels: enhancement

#449 Filters: Don't hide active filters
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceSelectionScene/SelectServiceButton.tsx
  src/Components/Table/CellContextMenu.tsx
  src/services/filters.test.ts
  src/services/filters.ts
  src/services/scenes.test.ts
  src/services/scenes.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement

#487 fix(table): fix negative width columns bug
  src/Components/Table/Table.tsx
Labels: bug
