Repository grafana/logs-drilldown, pull requests merged in 2024-07, with the labels that each got.

#495 UX: add search icon to field/label autocomplete dropdown
  src/Components/ServiceScene/Breakdowns/FieldSelector.tsx
Labels: ux

#503 Docs & dependency updates
  CHANGELOG.md
  README.md
  src/README.md
  src/plugin.json
Labels: documentation

#526 fix(lazy-load): add missing `isLazy` prop
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
Labels: bug

#484 feat(pattern): add a tooltip for each fields that shows statistics about the field.
  src/Components/ServiceScene/Breakdowns/Patterns/FilterByPatternsButton.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternFieldLabelStats.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternFieldLabelStatsRow.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsFrameScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTextSearch.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/analytics.ts
Labels: enhancement

#456 docs mvp
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/get-started/_index.md
  docs/sources/images/service_index.png
  docs/sources/labels-and-fields/_index.md
  docs/sources/patterns/_index.md
  docs/sources/troubleshooting/_index.md
  package.json
Labels: documentation, type/docs

#555 Services: State inconsistency across routes
  src/Components/LogExplorationPage.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceSelectionScene/SelectServiceButton.tsx
  src/services/metadata.ts
  src/services/routing.ts
Labels: bug

#562 Table: Use detected_level, fix low contrast background color & text
  src/Components/Table/DefaultCellComponent.tsx
  src/Components/Table/DefaultPill.tsx
  src/Components/Table/LogLineCellComponent.tsx
  src/Components/Table/LogLinePill.tsx
  src/Components/Table/constants.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: ui

#561 fixed broken link
  docs/sources/access/_index.md
Labels: type/docs

#506 Intercept banner
  src/Components/IndexScene/InterceptBanner.tsx
  src/Components/IndexScene/LayoutScene.tsx
Labels: chore

#582 docs: Copyedit for style and docs standards
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/get-started/_index.md
  docs/sources/images/fields.png
  docs/sources/images/labels.png
  docs/sources/images/patterns.png
  docs/sources/images/service_index.png
  docs/sources/images/sort-by-dropdown.png
  docs/sources/labels-and-fields/_index.md
  docs/sources/ordering/_index.md
  docs/sources/patterns/_index.md
  docs/sources/troubleshooting/_index.md
Labels: type/docs

#602 docs: Fix heading levels
  docs/sources/access/_index.md
Labels: type/docs

#605 docs: more standardization edits
  docs/sources/_index.md
  docs/sources/ordering/_index.md
Labels: type/docs

#610 docs: Update metadata with canonical URLs
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/get-started/_index.md
  docs/sources/labels-and-fields/_index.md
  docs/sources/ordering/_index.md
  docs/sources/patterns/_index.md
  docs/sources/troubleshooting/_index.md
Labels: type/docs

#620 Fields: fix loading forever when fields return empty
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
Labels: bug

#629 Service views: Prevent extra queries
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceSelectionScene/SelectServiceButton.tsx
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/fields.ts
  src/services/variableGetters.ts
Labels: bug

#632 Variables: move variable lookup to getter functions
  src/Components/IndexScene/IndexScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx
  src/Components/ServiceScene/LineFilterScene.tsx
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceSelectionScene/SelectServiceButton.tsx
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/scenes.ts
  src/services/variables.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: chore

#633 Order agnostic state comparison
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsFrameScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTextSearch.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/comparison.test.ts
  src/services/comparison.ts
  src/services/fields.ts
Labels: bug, chore

#644 Logs Volume: track filtering interactions
  src/Components/ServiceScene/LogsVolumePanel.tsx
  src/services/analytics.ts
Labels: chore

#630 LogsVolumePanel: remove unneccessary filters and parsers in query expression
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/LogsVolumePanel.tsx
  src/services/expressions.ts
  src/services/fields.ts
  src/services/variableGetters.ts
  src/services/variables.ts
Labels: bug
