Repository grafana/logs-drilldown, pull requests merged in 2025-01, with the labels that each got.

#979 Table: Show log text not preserved in URL state
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  src/Components/Table/Context/TableColumnsContext.tsx
  src/Components/Table/RawLogLineText.tsx
  src/Components/Table/TableProvider.tsx
  src/Components/Table/TableWrap.tsx
  src/services/testIds.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement

#978 Table: Column order not preserved in URL
  src/Components/ServiceScene/LogsTableScene.tsx
  src/services/comparison.test.ts
  src/services/comparison.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: bug

#982 chore: run `yarn audit fix`
  src/Components/Table/TableProvider.tsx
  src/Components/Table/TableWrap.tsx
  yarn.lock
Labels: chore

#983 Breakdowns: Add share menu
  project-words.txt
  src/Components/IndexScene/ShareButtonScene.tsx
  src/Components/ServiceScene/ActionBarScene.tsx
Labels: enhancement

#987 chore: clean up copy texts
  src/Components/IndexScene/ShareButtonScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/services/text.ts
Labels: debt

#963 Line filters: Regex support
  package.json
  src/Components/IndexScene/IndexScene.tsx
  src/Components/IndexScene/LayoutScene.tsx
  src/Components/IndexScene/LineFilterVariablesScene.tsx
  src/Components/IndexScene/PatternControls.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.test.ts
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.test.ts
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsLogsSampleScene.tsx
  src/Components/ServiceScene/Breakdowns/SearchInput.tsx
  src/Components/ServiceScene/LineFilter/LineFilterCaseSensitivityButton.tsx
  src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
  src/Components/ServiceScene/LineFilter/LineFilterScene.test.tsx
  src/Components/ServiceScene/LineFilter/LineFilterScene.tsx
  src/Components/ServiceScene/LineFilter/RegexIconButton.tsx
  src/Components/ServiceScene/LineFilterIcon.tsx
  src/Components/ServiceScene/LineFilterScene.test.tsx
  src/Components/ServiceScene/LineFilterScene.tsx
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/analytics.ts
  src/services/expressions.ts
  src/services/filterTypes.ts
  src/services/migrations.ts
  src/services/mixins.ts
  src/services/query.test.ts
  src/services/query.ts
  src/services/routing.ts
  src/services/scenes.ts
  src/services/store.ts
  src/services/variableGetters.ts
  src/services/variables.ts
  tests/appNavigation.spec.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/fixtures/explore.ts
  yarn.lock
Labels: enhancement

#992 Line filters: Allow backticks
  project-words.txt
  src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
  src/services/query.test.ts
  src/services/query.ts
Labels: enhancement

#994 fix: use urlUtil instead of UrlSearchParams
  src/Components/IndexScene/ShareButtonScene.tsx
  src/services/migrations.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/fixtures/explore.ts
Labels: bug

#996 fix(sorting): prevent sorting timeFields in place
  src/services/logsFrame.test.ts
  src/services/logsFrame.ts
Labels: bug

#997 Link extensions: Add support for line filters
  package.json
  src/Components/IndexScene/LineFilterVariablesScene.tsx
  src/Components/ServiceScene/LineFilter/LineFilterCaseSensitivityButton.tsx
  src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
  src/Components/ServiceScene/LineFilter/LineFilterScene.test.tsx
  src/Components/ServiceScene/LineFilter/LineFilterScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/services/extensions/links.test.ts
  src/services/extensions/links.ts
  src/services/filterTypes.ts
  src/services/logqlMatchers.ts
  src/services/migrations.ts
  src/services/query.test.ts
  src/services/query.ts
  tests/exploreServicesBreakDown.spec.ts
  yarn.lock
Labels: enhancement

#1000 Link extensions: fix false positive introduced by field filters
  src/services/extensions/links.test.ts
  src/services/logqlMatchers.ts
Labels: bug

#999 Link extensions: add support for fields
  package.json
  src/Components/ServiceScene/Breakdowns/NumericFilterPopoverScene.tsx
  src/services/extensions/links.test.ts
  src/services/extensions/links.ts
  src/services/fields.test.ts
  src/services/fields.ts
  src/services/fieldsTypes.ts
  src/services/filterTypes.ts
  src/services/logqlMatchers.ts
  src/services/lokiQuery.ts
  yarn.lock
Labels: enhancement

#1003 Patterns: patterns containing quotes break when added as filter
  src/services/query.test.ts
  src/services/query.ts
Labels: bug

#1012 Service selection: make volume search case-insensitive
  src/services/query.test.ts
  src/services/query.ts
  tests/appNavigation.spec.ts
  tests/exploreServices.spec.ts
Labels: enhancement

#1010 Regex labels: support queries from explore
  src/Components/IndexScene/IndexScene.tsx
  src/Components/IndexScene/ShowLogsButtonScene.tsx
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceSelectionScene/AddLabelToFiltersHeaderActionScene.tsx
  src/services/TagKeysProviders.ts
  src/services/TagValuesProviders.ts
  src/services/extensions/links.test.ts
  src/services/extensions/links.ts
  src/services/filterTypes.ts
  src/services/levels.test.ts
  src/services/levels.ts
  src/services/logqlMatchers.ts
  src/services/operators.ts
  src/services/query.test.ts
  src/services/query.ts
Labels: enhancement

#1018 Table: Open in Explore links do not add labelFieldName
  src/Components/ServiceScene/GoToExploreButton.test.tsx
  src/Components/ServiceScene/GoToExploreButton.tsx
Labels: bug
