Repository grafana/logs-drilldown, pull requests merged in 2025-08, with the labels that each got.

#1374 feat(fields): field name view
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/Breakdowns/FieldSelector.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/Breakdowns/ShowErrorPanelToggle.tsx
  src/Components/ServiceScene/Breakdowns/ShowFieldDisplayToggle.tsx
  src/services/analytics.ts
  src/services/fields.ts
  src/services/store.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: enhancement

#1477 fix(assistant): move `getObservablePluginLinks` check to `@grafana/assistant` package
  package.json
  src/Components/IndexScene/IndexScene.tsx
  src/Components/Panels/PanelMenu.tsx
  yarn.lock
Labels: chore

#1491 feat: grafana assistant expr based links
  src/plugin.json
  src/services/extensions/links.test.ts
  src/services/extensions/links.ts
Labels: enhancement

#1510 fix(ServiceSelectionScene): roll back showing stored displayed fields
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/store.ts
Labels: bug
