Repository grafana/logs-drilldown, pull requests merged in 2025-07, with the labels that each got.

#1358 feat(fields): calculate sparsity on errored/partial data
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
Labels: enhancement

#1368 fix(JSON): detected fields not always getting called on activation
  src/Components/ServiceScene/LogsJsonScene.tsx
  tests/exploreServicesJsonBreakDown.spec.ts
Labels: bug

#1376 feat(Embbedding): open embedding API for default line filters
  src/Components/EmbeddedLogsExploration/EmbeddedLogs.tsx
  src/Components/IndexScene/IndexScene.tsx
  src/Components/IndexScene/types.ts
  src/Components/Pages.tsx
  tests/appNavigation.spec.ts
  tests/embed.spec.ts
  tests/exploreServicesJsonBreakDown.spec.ts
Labels: embedding

#1390 fix: limit patterns to 500
  src/services/datasource.ts
Labels: bug

#1402 fix(JSON): Allow changing root if no JSON logs present
  src/Components/ServiceScene/JSONPanel/JsonRootNodeNavigation.tsx
  src/Components/ServiceScene/JSONPanel/LabelRenderer.tsx
  src/Components/ServiceScene/JSONPanel/ReRootJSONButton.tsx
  src/Components/ServiceScene/LogsJsonScene.tsx
Labels: bug, chore

#1408 docs: Add links to videos on Logs Drilldown
  docs/sources/get-started/_index.md
Labels: type/docs

#1406 feat(JSON): share link to line
  package.json
  playwright.config.ts
  src/Components/Buttons/CopyToClipboardButton.tsx
  src/Components/ServiceScene/JSONPanel/ItemString.tsx
  src/Components/ServiceScene/JSONPanel/LogsJsonComponent.tsx
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/services/fields.ts
  tests/exploreServicesJsonBreakDown.spec.ts
  yarn.lock
Labels: enhancement

#1420 feat(JSON): links
  provisioning/datasources/default.yaml
  src/Components/ServiceScene/JSONPanel/ItemString.tsx
  src/Components/ServiceScene/JSONPanel/JsonLinkButton.tsx
  src/Components/ServiceScene/JSONPanel/LabelRenderer.tsx
  src/Components/ServiceScene/JSONPanel/ValueRenderer.tsx
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/services/JSONViz.ts
  src/services/derivedFields.ts
  src/services/narrowing.ts
  tests/exploreServicesJsonBreakDown.spec.ts
Labels: enhancement

#1422 feat(table): column width estimator and toggle logsPanelControls
  .eslintignore
  docker-compose.local.yaml
  src/Components/ServiceScene/LogListControls.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  src/Components/Table/LogLineCellComponent.tsx
  src/Components/Table/LogsTableHeader.tsx
  src/Components/Table/LogsTableHeaderWrap.tsx
  src/Components/Table/Table.tsx
Labels: enhancement

#1438 chore(embedded): add tracking on go to explore button used in embedded UI
  src/Components/EmbeddedLogsExploration/EmbeddedLinkScene.tsx
  src/services/analytics.ts
Labels: chore

#1440 chore(analytics): on query event
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/analytics.ts
Labels: chore

#1459 feat(Patterns): filter by level
  docker-compose-syslog.dev.yaml
  docker-compose.dev.yaml
  docker-compose.local.yaml
  docker-compose.yaml
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsFrameScene.tsx
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/datasource.test.ts
  src/services/datasource.ts
  src/services/panel.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: bug, enhancement

#1468 fix(ServiceSelection): header offset conflict with sidebar apps
  src/Components/IndexScene/VariableLayoutScene.tsx
Labels: bug
