Repository grafana/logs-drilldown, pull requests merged in 2025-06, with the labels that each got.

#1309 docs: fix incomplete sentence
  docs/sources/patterns/_index.md
Labels: type/docs

#1294 feat(embedding): Embedded Service Scene Component
  cspell.config.json
  src/Components/EmbeddedLogsExploration/EmbeddedLinkScene.tsx
  src/Components/EmbeddedLogsExploration/EmbeddedLogs.tsx
  src/Components/EmbeddedLogsExploration/types.ts
  src/Components/IndexScene/IndexScene.tsx
  src/Components/IndexScene/VariableLayoutScene.tsx
  src/Components/LogExplorationPage.tsx
  src/Components/Pages.tsx
  src/Components/ServiceScene/ActionBarScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/ServiceScene/ServiceSceneConstants.ts
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/module.tsx
  src/plugin.json
  src/services/datasource.ts
  src/services/enums.ts
  src/services/extensions/exposedComponents.tsx
  src/services/extensions/links.ts
  src/services/logqlMatchers.ts
  src/services/metadata.ts
  src/services/narrowing.ts
  src/services/navigate.ts
  src/services/plugin.ts
  src/services/routing.ts
  src/services/variableHelpers.ts
  tests/embed.spec.ts
  tests/fixtures/explore.ts
Labels: enhancement

#1315 feat(embedding): Embedded readonly filters
  .eslintignore
  .prettierignore
  package.json
  src/Components/EmbeddedLogsExploration/types.ts
  src/Components/IndexScene/IndexScene.tsx
  src/Components/Pages.tsx
  src/Components/ServiceScene/LogsPanelError.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/services/LabelFiltersVariable.tsx
  src/services/LogsSceneQueryRunner.ts
  src/services/panel.ts
  src/services/variableHelpers.ts
  tests/embed.spec.ts
  yarn.lock
Labels: enhancement

#1301 fix(JSON): add second json parser stage
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/services/query.ts
Labels: bug

#1302 fix(logs-panel): infinite scroll broken
  src/services/variables.ts
Labels: bug

#1346 feat(FieldsBreakdown): Show panels with errors
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LayoutSwitcher.test.tsx
  src/Components/ServiceScene/Breakdowns/LayoutSwitcher.tsx
  src/Components/ServiceScene/Breakdowns/QueryErrorAlert.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/services/analytics.ts
  src/services/shardQuerySplitting.ts
  src/services/store.ts
Labels: enhancement, ui

#1353 feat(EmbeddedLogs): embedded logs url parameter namespace
  .gitignore
  .nvmrc
  .prettierignore
  package.json
  src/Components/EmbeddedLogsExploration/EmbeddedLogs.tsx
  yarn.lock
Labels: enhancement

#1363 fix(logs-volume): don't run volume query when collapsed
  src/Components/ServiceScene/LogsVolumePanel.tsx
Labels: bug
