Repository grafana/logs-drilldown, pull requests merged in 2025-03, with the labels that each got.

#1129 Logs Panel: Add metadata to logged error
  src/Components/ServiceScene/LogsPanelScene.tsx
Labels: chore

#1135 E2E: Address flakey test
  tests/exploreServicesBreakDown.spec.ts
Labels: chore

#1143 Docs: update readme to include discover_log_levels config requirement
  README.md
Labels: type/docs

#1146 feat: add critical/fatal log level
  src/services/panel.test.ts
  src/services/panel.ts
Labels: bug

#1145 Label selection: set step as 10s for aggregated metric queries
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/lokiQuery.ts
Labels: enhancement
