Repository grafana/logs-drilldown, pull requests merged in 2025-09, with the labels that each got.

#1537 feat(LineLimitScene): error message, invalidation state
  src/Components/ServiceScene/JSONLogsScene.tsx
  src/Components/ServiceScene/JSONPanel/LogsJSONComponent.tsx
  src/Components/ServiceScene/LineLimitScene.tsx
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  tests/exploreServicesJsonBreakDown.spec.ts
Labels: enhancement

#1548 chore: upgrade Scenes and Grafana deps
  package.json
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsLogsSampleScene.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  tests/config/grafana-versions-supported.ts
  yarn.lock
Labels: chore

#1549 feat(embedded): allow resetting filters
  src/Components/EmbeddedLogsExploration/EmbeddedLinkScene.tsx
  src/Components/EmbeddedLogsExploration/EmbeddedLogs.tsx
  src/Components/EmbeddedLogsExploration/types.ts
  src/Components/IndexScene/IndexScene.tsx
  src/Components/IndexScene/ResetFiltersButton.tsx
  src/Components/IndexScene/VariableLayoutScene.tsx
  src/Components/IndexScene/types.ts
  src/Components/Pages.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/services/ReadOnlyAdHocFiltersVariable.tsx
  src/services/variableHelpers.test.ts
  src/services/variableHelpers.ts
  tests/embed.spec.ts
  tests/fixtures/explore.ts
Labels: enhancement, embedding

#1552 chore: fix runtime error when viewing label value breakdown
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
Labels: bug
