Repository grafana/logs-drilldown, pull requests merged in 2025-05, with the labels that each got.

#1235 chore(docker-compose): update loki to 3.5.0
  docker-compose.dev.yaml
  docker-compose.local.yaml
  docker-compose.yaml
Labels: chore

#1237 fix(table): missing line filter
  src/Components/ServiceScene/LogsListScene.tsx
Labels: bug, no-changelog

#1236 fix: Empty results layout in JSON and Table
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
Labels: no-changelog

#1238 fix(line-filters): Expand no longer working.
  src/Components/ServiceScene/Breakdowns/LineFilterInput.tsx
Labels: bug, no-changelog

#1248 docs: Updating screenshots and docs
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/get-started/_index.md
  docs/sources/labels-and-fields/_index.md
  docs/sources/ordering/_index.md
  docs/sources/patterns/_index.md
  docs/sources/troubleshooting/_index.md
  docs/sources/viewing-json-logs/_index.md
Labels: type/docs

#1247 chore(e2e): clean up & flake prevention
  playwright.config.ts
  tests/appNavigation.spec.ts
  tests/exploreServices.spec.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/exploreServicesJsonBreakDown.spec.ts
  tests/fixtures/explore.ts
Labels: chore

#1251 docs: Addressing review comments #1248
  docs/sources/access/_index.md
  docs/sources/get-started/_index.md
  docs/sources/labels-and-fields/_index.md
  docs/sources/ordering/_index.md
  docs/sources/troubleshooting/_index.md
  docs/sources/viewing-json-logs/_index.md
Labels: type/docs

#1270 chore: update grafana assets to 11.6.1
  package.json
  yarn.lock
Labels: chore

#1276 fix(investigations): interpolate jsonFields
  src/Components/ServiceScene/Breakdowns/AddToInvestigationButton.tsx
Labels: bug
