Repository grafana/logs-drilldown, pull requests merged in 2025-04, with the labels that each got.

#1148 PanelMenu: Make extensions compatibly with different Grafana versions
  src/Components/Panels/PanelMenu.tsx
Labels: enhancement

#1153 Line filter: Fix error being thrown when toggling case sensitivity with empty value
  src/services/query.test.ts
  src/services/query.ts
Labels: bug

#1162 chore: (grafana 11.6) - update to latest grafana 11.6 and latest plugin libraries, remove comments
  .github/workflows/cp-update.yml
  cypress.json
  docker-compose.yaml
  package.json
  src/Components/GrotError.test.tsx
  src/Components/GrotError.tsx
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/Panels/ValueSummary.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/Components/ServiceScene/LogsTableScene.tsx
  src/Components/ServiceScene/LogsVolumePanel.tsx
  src/plugin.json
  src/services/fields.ts
  yarn.lock
Labels: chore

#1176 SubPath: Fix url sharing and line filter migrations
  .eslintrc
  docker-compose.dev.yaml
  docker-compose.local.yaml
  playwright.config.ts
  src/Components/OpenInLogsDrilldownButton/OpenInLogsDrilldownButton.test.tsx
  src/Components/Pages.tsx
  src/services/extensions/links.ts
  src/services/migrations.ts
  src/services/text.test.ts
  src/services/text.ts
  tests/fixtures/explore.ts
Labels: bug

#1175 chore: (provisioning) - add loki datasource and env
  .env.template
  .gitignore
  docker-compose.local.yaml
  provisioning/datasources/default.yaml
Labels: chore

#1186 Patterns: Percentage in table is relative to current pattern search results
  src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
Labels: bug

#1188 Service selection: Simplify panel buttons
  src/Components/IndexScene/LayoutScene.tsx
  src/Components/IndexScene/VariableLayoutScene.tsx
  src/Components/ServiceSelectionScene/AddLabelToFiltersHeaderActionScene.tsx
  src/Components/ServiceSelectionScene/SelectServiceButton.tsx
  src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
  src/services/testIds.ts
  tests/appNavigation.spec.ts
  tests/exploreServices.spec.ts
  tests/fixtures/explore.ts
Labels: enhancement, ux

#1190 Line filters: Client regex validation
  package.json
  src/Components/ServiceScene/Breakdowns/LineFilterInput.tsx
  src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
  src/Components/ServiceScene/LineFilter/LineFilterScene.test.tsx
  src/Components/ServiceScene/LineFilter/LineFilterScene.tsx
  src/services/narrowing.ts
  yarn.lock
Labels: enhancement

#1019 Scenes: Updating to v6
  .config/webpack/webpack.config.ts
  .cprc.json
  package.json
  playwright.config.ts
  src/Components/LogExplorationPage.tsx
  src/Components/Pages.tsx
  src/Components/ServiceScene/LogsPanelScene.tsx
  src/services/CustomConstantVariable.ts
  src/services/LogsSceneQueryRunner.ts
  src/services/logqlMatchers.ts
  src/services/routing.ts
  yarn.lock
Labels: scenes

#1122 JSON viz: MVP
  .eslintrc
  docker-compose.dev.yaml
  docker-compose.local.yaml
  docker-compose.yaml
  generator/flog/log.go
  package.json
  src/Components/IndexScene/IndexScene.tsx
  src/Components/IndexScene/LayoutScene.tsx
  src/Components/IndexScene/VariableLayoutScene.tsx
  src/Components/Pages.tsx
  src/Components/Panels/PanelMenu.tsx
  src/Components/ServiceScene/ActionBarScene.tsx
  src/Components/ServiceScene/BreakdownViews.ts
  src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
  src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.test.ts
  src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.test.ts
  src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/LabelsAggregatedBreakdownScene.tsx
  src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
  src/Components/ServiceScene/GoToExploreButton.tsx
  src/Components/ServiceScene/JSONPanel/JSONFilterNestedNodeButton.tsx
  src/Components/ServiceScene/JSONPanel/JSONFilterValueButton.tsx
  src/Components/ServiceScene/JSONPanel/ReRootJSONButton.tsx
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/Components/ServiceScene/LogsListScene.tsx
  src/Components/ServiceScene/ServiceScene.tsx
  src/Components/Table/LogsHeaderActions.tsx
  src/__mocks__/@gtk-grafana/react-json-tree.tsx
  src/services/JSONViz.ts
  src/services/datasource.test.ts
  src/services/datasource.ts
  src/services/enums.ts
  src/services/expressions.ts
  src/services/fields.ts
  src/services/filterTypes.ts
  src/services/filters.ts
  src/services/labels.ts
  src/services/logsFrame.ts
  src/services/narrowing.ts
  src/services/navigate.test.ts
  src/services/navigate.ts
  src/services/panel.ts
  src/services/query.ts
  src/services/routing.test.ts
  src/services/routing.ts
  src/services/store.ts
  src/services/variableGetters.ts
  src/services/variables.ts
  tests/appNavigation.spec.ts
  tests/exploreServicesBreakDown.spec.ts
  tests/exploreServicesJsonBreakDown.spec.ts
  tests/exploreServicesJsonMixedBreakDown.spec.ts
  tests/fixtures/explore.ts
  yarn.lock
Labels: enhancement, viz, JSON

#1151 JSON: DrillUp breadcrumbs
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/services/JSONViz.ts
  tests/exploreServicesJsonBreakDown.spec.ts
  yarn.lock
Labels: enhancement, viz, JSON

#1184 JSON Viz: add rudderstack event for filters/reroot in json viz
  project-words.txt
  src/Components/ServiceScene/LogsJsonScene.tsx
  src/services/analytics.ts
  tests/exploreServicesBreakDown.spec.ts
Labels: chore, viz, JSON

#1214 Fix: JSON - line format containing unsupported chars
  src/Components/ServiceScene/LogsJsonScene.tsx
Labels: bug, JSON
